In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/saura/OneDrive/Desktop/FBS/Data Analysis/Datasets-20260831T104834Z-1-001/Datasets/student_10.csv")
df.head()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     object
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 532.0+ bytes

In [5]:
df['Class']==12

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
Name: Class, dtype: bool

In [6]:
df[df['Class']==12]

         Date  Student ID  Class  Study hrs  Percentage
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [9]:
df[df['Percentage']>80]

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0
9  12-07-2021      1010.0     12        6.0        85.0

In [8]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [15]:
df['Student ID']==1008.0

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: Student ID, dtype: bool

In [10]:
df[df['Student ID']==1008.0]

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0

In [12]:
df.loc[df['Student ID']==1008.0,'Percentage']=95

In [13]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        95.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [16]:
df1=pd.DataFrame({'id':[101,102,103],'name':['Shraddha','Saurabh','Pravin']})
df1

    id      name
0  101  Shraddha
1  102   Saurabh
2  103    Pravin

In [17]:
df2=pd.DataFrame({'dept_id':[1,2,1],'dname':['Admin','IT','Admin']})
df2

   dept_id  dname
0        1  Admin
1        2     IT
2        1  Admin

## Concat

In [19]:
pd.concat([df1,df2],axis=1)

    id      name  dept_id  dname
0  101  Shraddha        1  Admin
1  102   Saurabh        2     IT
2  103    Pravin        1  Admin

In [20]:
pd.concat([df1,df2])

      id      name  dept_id  dname
0  101.0  Shraddha      NaN    NaN
1  102.0   Saurabh      NaN    NaN
2  103.0    Pravin      NaN    NaN
0    NaN       NaN      1.0  Admin
1    NaN       NaN      2.0     IT
2    NaN       NaN      1.0  Admin

In [26]:
emp=pd.DataFrame({'id':[101,102,103,104],
                  'name':['Omkar','Parth','Adinath','Pratik'],
                 'did':[1,2,1,4]})
emp

    id     name  did
0  101    Omkar    1
1  102    Parth    2
2  103  Adinath    1
3  104   Pratik    4

In [22]:
dept=pd.DataFrame({'did':[1,2,3],'dname':['Admin','IT','Sales']})
dept

   did  dname
0    1  Admin
1    2     IT
2    3  Sales

## Merge

In [27]:
pd.merge(emp,dept,how='inner')

    id     name  did  dname
0  101    Omkar    1  Admin
1  102    Parth    2     IT
2  103  Adinath    1  Admin

In [28]:
pd.merge(emp,dept,how='left')

    id     name  did  dname
0  101    Omkar    1  Admin
1  102    Parth    2     IT
2  103  Adinath    1  Admin
3  104   Pratik    4    NaN

In [29]:
pd.merge(emp,dept,how='right')

      id     name  did  dname
0  101.0    Omkar    1  Admin
1  103.0  Adinath    1  Admin
2  102.0    Parth    2     IT
3    NaN      NaN    3  Sales

In [32]:
pd.merge(emp,dept,left_on='did',right_on='didt_id')

KeyError: 'didt_id'